/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChatgptSkillsRouteImport } from './routes/chatgpt-skills'
import { Route as ClaudeSkillsRouteImport } from './routes/claude-skills'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CursorSkillsRouteImport } from './routes/cursor-skills'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as GithubCopilotSkillsRouteImport } from './routes/github-copilot-skills'
import { Route as GrokSkillsRouteImport } from './routes/grok-skills'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as McpSkillsRouteImport } from './routes/mcp-skills'
import { Route as PerplexitySkillsRouteImport } from './routes/perplexity-skills'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SuperhumanGoSkillsRouteImport } from './routes/superhuman-go-skills'
import { Route as WordpressSkillsRouteImport } from './routes/wordpress-skills'
import { Route as Char91DotwellKnownChar93ApiCatalogRouteImport } from './routes/[.well-known]/api-catalog'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as ApiPublicSkillsRouteImport } from './routes/api/public/skills'
import { Route as ApiPublicV1CapabilitiesRouteImport } from './routes/api/public/v1/capabilities'
import { Route as ApiPublicV1SkillsRouteImport } from './routes/api/public/v1/skills'
import { Route as ApiPublicSkillsAgentAgentRouteImport } from './routes/api/public/skills/agent/$agent'
import { Route as ApiPublicV1SkillsIdRouteImport } from './routes/api/public/v1/skills/$id'
import { Route as ApiPublicV1SkillsAgentAgentRouteImport } from './routes/api/public/v1/skills/agent/$agent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatgptSkillsRoute = ChatgptSkillsRouteImport.update({
  id: '/chatgpt-skills',
  path: '/chatgpt-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeSkillsRoute = ClaudeSkillsRouteImport.update({
  id: '/claude-skills',
  path: '/claude-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CursorSkillsRoute = CursorSkillsRouteImport.update({
  id: '/cursor-skills',
  path: '/cursor-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubCopilotSkillsRoute = GithubCopilotSkillsRouteImport.update({
  id: '/github-copilot-skills',
  path: '/github-copilot-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const GrokSkillsRoute = GrokSkillsRouteImport.update({
  id: '/grok-skills',
  path: '/grok-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const McpSkillsRoute = McpSkillsRouteImport.update({
  id: '/mcp-skills',
  path: '/mcp-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const PerplexitySkillsRoute = PerplexitySkillsRouteImport.update({
  id: '/perplexity-skills',
  path: '/perplexity-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperhumanGoSkillsRoute = SuperhumanGoSkillsRouteImport.update({
  id: '/superhuman-go-skills',
  path: '/superhuman-go-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const WordpressSkillsRoute = WordpressSkillsRouteImport.update({
  id: '/wordpress-skills',
  path: '/wordpress-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93ApiCatalogRoute =
  Char91DotwellKnownChar93ApiCatalogRouteImport.update({
    id: '/.well-known/api-catalog',
    path: '/.well-known/api-catalog',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSkillsRoute = ApiPublicSkillsRouteImport.update({
  id: '/api/public/skills',
  path: '/api/public/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CapabilitiesRoute = ApiPublicV1CapabilitiesRouteImport.update({
  id: '/api/public/v1/capabilities',
  path: '/api/public/v1/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SkillsRoute = ApiPublicV1SkillsRouteImport.update({
  id: '/api/public/v1/skills',
  path: '/api/public/v1/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSkillsAgentAgentRoute =
  ApiPublicSkillsAgentAgentRouteImport.update({
    id: '/agent/$agent',
    path: '/agent/$agent',
    getParentRoute: () => ApiPublicSkillsRoute,
  } as any)
const ApiPublicV1SkillsIdRoute = ApiPublicV1SkillsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1SkillsRoute,
} as any)
const ApiPublicV1SkillsAgentAgentRoute =
  ApiPublicV1SkillsAgentAgentRouteImport.update({
    id: '/agent/$agent',
    path: '/agent/$agent',
    getParentRoute: () => ApiPublicV1SkillsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chatgpt-skills': typeof ChatgptSkillsRoute
  '/claude-skills': typeof ClaudeSkillsRoute
  '/contact': typeof ContactRoute
  '/cursor-skills': typeof CursorSkillsRoute
  '/developers': typeof DevelopersRoute
  '/github-copilot-skills': typeof GithubCopilotSkillsRoute
  '/grok-skills': typeof GrokSkillsRoute
  '/library': typeof LibraryRoute
  '/licenses': typeof LicensesRoute
  '/mcp': typeof McpRoute
  '/mcp-skills': typeof McpSkillsRoute
  '/perplexity-skills': typeof PerplexitySkillsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/superhuman-go-skills': typeof SuperhumanGoSkillsRoute
  '/wordpress-skills': typeof WordpressSkillsRoute
  '/.well-known/api-catalog': typeof Char91DotwellKnownChar93ApiCatalogRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/api': typeof DocsApiRoute
  '/s/$token': typeof STokenRoute
  '/api/public/skills': typeof ApiPublicSkillsRouteWithChildren
  '/api/public/v1/capabilities': typeof ApiPublicV1CapabilitiesRoute
  '/api/public/v1/skills': typeof ApiPublicV1SkillsRouteWithChildren
  '/api/public/skills/agent/$agent': typeof ApiPublicSkillsAgentAgentRoute
  '/api/public/v1/skills/$id': typeof ApiPublicV1SkillsIdRoute
  '/api/public/v1/skills/agent/$agent': typeof ApiPublicV1SkillsAgentAgentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chatgpt-skills': typeof ChatgptSkillsRoute
  '/claude-skills': typeof ClaudeSkillsRoute
  '/contact': typeof ContactRoute
  '/cursor-skills': typeof CursorSkillsRoute
  '/developers': typeof DevelopersRoute
  '/github-copilot-skills': typeof GithubCopilotSkillsRoute
  '/grok-skills': typeof GrokSkillsRoute
  '/library': typeof LibraryRoute
  '/licenses': typeof LicensesRoute
  '/mcp': typeof McpRoute
  '/mcp-skills': typeof McpSkillsRoute
  '/perplexity-skills': typeof PerplexitySkillsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/superhuman-go-skills': typeof SuperhumanGoSkillsRoute
  '/wordpress-skills': typeof WordpressSkillsRoute
  '/.well-known/api-catalog': typeof Char91DotwellKnownChar93ApiCatalogRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/api': typeof DocsApiRoute
  '/s/$token': typeof STokenRoute
  '/api/public/skills': typeof ApiPublicSkillsRouteWithChildren
  '/api/public/v1/capabilities': typeof ApiPublicV1CapabilitiesRoute
  '/api/public/v1/skills': typeof ApiPublicV1SkillsRouteWithChildren
  '/api/public/skills/agent/$agent': typeof ApiPublicSkillsAgentAgentRoute
  '/api/public/v1/skills/$id': typeof ApiPublicV1SkillsIdRoute
  '/api/public/v1/skills/agent/$agent': typeof ApiPublicV1SkillsAgentAgentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chatgpt-skills': typeof ChatgptSkillsRoute
  '/claude-skills': typeof ClaudeSkillsRoute
  '/contact': typeof ContactRoute
  '/cursor-skills': typeof CursorSkillsRoute
  '/developers': typeof DevelopersRoute
  '/github-copilot-skills': typeof GithubCopilotSkillsRoute
  '/grok-skills': typeof GrokSkillsRoute
  '/library': typeof LibraryRoute
  '/licenses': typeof LicensesRoute
  '/mcp': typeof McpRoute
  '/mcp-skills': typeof McpSkillsRoute
  '/perplexity-skills': typeof PerplexitySkillsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/superhuman-go-skills': typeof SuperhumanGoSkillsRoute
  '/wordpress-skills': typeof WordpressSkillsRoute
  '/.well-known/api-catalog': typeof Char91DotwellKnownChar93ApiCatalogRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/api': typeof DocsApiRoute
  '/s/$token': typeof STokenRoute
  '/api/public/skills': typeof ApiPublicSkillsRouteWithChildren
  '/api/public/v1/capabilities': typeof ApiPublicV1CapabilitiesRoute
  '/api/public/v1/skills': typeof ApiPublicV1SkillsRouteWithChildren
  '/api/public/skills/agent/$agent': typeof ApiPublicSkillsAgentAgentRoute
  '/api/public/v1/skills/$id': typeof ApiPublicV1SkillsIdRoute
  '/api/public/v1/skills/agent/$agent': typeof ApiPublicV1SkillsAgentAgentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chatgpt-skills'
    | '/claude-skills'
    | '/contact'
    | '/cursor-skills'
    | '/developers'
    | '/github-copilot-skills'
    | '/grok-skills'
    | '/library'
    | '/licenses'
    | '/mcp'
    | '/mcp-skills'
    | '/perplexity-skills'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/superhuman-go-skills'
    | '/wordpress-skills'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-protected-resource'
    | '/api/$'
    | '/docs/api'
    | '/s/$token'
    | '/api/public/skills'
    | '/api/public/v1/capabilities'
    | '/api/public/v1/skills'
    | '/api/public/skills/agent/$agent'
    | '/api/public/v1/skills/$id'
    | '/api/public/v1/skills/agent/$agent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chatgpt-skills'
    | '/claude-skills'
    | '/contact'
    | '/cursor-skills'
    | '/developers'
    | '/github-copilot-skills'
    | '/grok-skills'
    | '/library'
    | '/licenses'
    | '/mcp'
    | '/mcp-skills'
    | '/perplexity-skills'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/superhuman-go-skills'
    | '/wordpress-skills'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-protected-resource'
    | '/api/$'
    | '/docs/api'
    | '/s/$token'
    | '/api/public/skills'
    | '/api/public/v1/capabilities'
    | '/api/public/v1/skills'
    | '/api/public/skills/agent/$agent'
    | '/api/public/v1/skills/$id'
    | '/api/public/v1/skills/agent/$agent'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chatgpt-skills'
    | '/claude-skills'
    | '/contact'
    | '/cursor-skills'
    | '/developers'
    | '/github-copilot-skills'
    | '/grok-skills'
    | '/library'
    | '/licenses'
    | '/mcp'
    | '/mcp-skills'
    | '/perplexity-skills'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/superhuman-go-skills'
    | '/wordpress-skills'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-protected-resource'
    | '/api/$'
    | '/docs/api'
    | '/s/$token'
    | '/api/public/skills'
    | '/api/public/v1/capabilities'
    | '/api/public/v1/skills'
    | '/api/public/skills/agent/$agent'
    | '/api/public/v1/skills/$id'
    | '/api/public/v1/skills/agent/$agent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatgptSkillsRoute: typeof ChatgptSkillsRoute
  ClaudeSkillsRoute: typeof ClaudeSkillsRoute
  ContactRoute: typeof ContactRoute
  CursorSkillsRoute: typeof CursorSkillsRoute
  DevelopersRoute: typeof DevelopersRoute
  GithubCopilotSkillsRoute: typeof GithubCopilotSkillsRoute
  GrokSkillsRoute: typeof GrokSkillsRoute
  LibraryRoute: typeof LibraryRoute
  LicensesRoute: typeof LicensesRoute
  McpRoute: typeof McpRoute
  McpSkillsRoute: typeof McpSkillsRoute
  PerplexitySkillsRoute: typeof PerplexitySkillsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuperhumanGoSkillsRoute: typeof SuperhumanGoSkillsRoute
  WordpressSkillsRoute: typeof WordpressSkillsRoute
  Char91DotwellKnownChar93ApiCatalogRoute: typeof Char91DotwellKnownChar93ApiCatalogRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DocsApiRoute: typeof DocsApiRoute
  STokenRoute: typeof STokenRoute
  ApiPublicSkillsRoute: typeof ApiPublicSkillsRouteWithChildren
  ApiPublicV1CapabilitiesRoute: typeof ApiPublicV1CapabilitiesRoute
  ApiPublicV1SkillsRoute: typeof ApiPublicV1SkillsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatgpt-skills': {
      id: '/chatgpt-skills'
      path: '/chatgpt-skills'
      fullPath: '/chatgpt-skills'
      preLoaderRoute: typeof ChatgptSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-skills': {
      id: '/claude-skills'
      path: '/claude-skills'
      fullPath: '/claude-skills'
      preLoaderRoute: typeof ClaudeSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursor-skills': {
      id: '/cursor-skills'
      path: '/cursor-skills'
      fullPath: '/cursor-skills'
      preLoaderRoute: typeof CursorSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github-copilot-skills': {
      id: '/github-copilot-skills'
      path: '/github-copilot-skills'
      fullPath: '/github-copilot-skills'
      preLoaderRoute: typeof GithubCopilotSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grok-skills': {
      id: '/grok-skills'
      path: '/grok-skills'
      fullPath: '/grok-skills'
      preLoaderRoute: typeof GrokSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-skills': {
      id: '/mcp-skills'
      path: '/mcp-skills'
      fullPath: '/mcp-skills'
      preLoaderRoute: typeof McpSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perplexity-skills': {
      id: '/perplexity-skills'
      path: '/perplexity-skills'
      fullPath: '/perplexity-skills'
      preLoaderRoute: typeof PerplexitySkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superhuman-go-skills': {
      id: '/superhuman-go-skills'
      path: '/superhuman-go-skills'
      fullPath: '/superhuman-go-skills'
      preLoaderRoute: typeof SuperhumanGoSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wordpress-skills': {
      id: '/wordpress-skills'
      path: '/wordpress-skills'
      fullPath: '/wordpress-skills'
      preLoaderRoute: typeof WordpressSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof Char91DotwellKnownChar93ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/skills': {
      id: '/api/public/skills'
      path: '/api/public/skills'
      fullPath: '/api/public/skills'
      preLoaderRoute: typeof ApiPublicSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/capabilities': {
      id: '/api/public/v1/capabilities'
      path: '/api/public/v1/capabilities'
      fullPath: '/api/public/v1/capabilities'
      preLoaderRoute: typeof ApiPublicV1CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/skills': {
      id: '/api/public/v1/skills'
      path: '/api/public/v1/skills'
      fullPath: '/api/public/v1/skills'
      preLoaderRoute: typeof ApiPublicV1SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/skills/agent/$agent': {
      id: '/api/public/skills/agent/$agent'
      path: '/agent/$agent'
      fullPath: '/api/public/skills/agent/$agent'
      preLoaderRoute: typeof ApiPublicSkillsAgentAgentRouteImport
      parentRoute: typeof ApiPublicSkillsRoute
    }
    '/api/public/v1/skills/$id': {
      id: '/api/public/v1/skills/$id'
      path: '/$id'
      fullPath: '/api/public/v1/skills/$id'
      preLoaderRoute: typeof ApiPublicV1SkillsIdRouteImport
      parentRoute: typeof ApiPublicV1SkillsRoute
    }
    '/api/public/v1/skills/agent/$agent': {
      id: '/api/public/v1/skills/agent/$agent'
      path: '/agent/$agent'
      fullPath: '/api/public/v1/skills/agent/$agent'
      preLoaderRoute: typeof ApiPublicV1SkillsAgentAgentRouteImport
      parentRoute: typeof ApiPublicV1SkillsRoute
    }
  }
}

interface ApiPublicSkillsRouteChildren {
  ApiPublicSkillsAgentAgentRoute: typeof ApiPublicSkillsAgentAgentRoute
}

const ApiPublicSkillsRouteChildren: ApiPublicSkillsRouteChildren = {
  ApiPublicSkillsAgentAgentRoute: ApiPublicSkillsAgentAgentRoute,
}

const ApiPublicSkillsRouteWithChildren = ApiPublicSkillsRoute._addFileChildren(
  ApiPublicSkillsRouteChildren,
)

interface ApiPublicV1SkillsRouteChildren {
  ApiPublicV1SkillsIdRoute: typeof ApiPublicV1SkillsIdRoute
  ApiPublicV1SkillsAgentAgentRoute: typeof ApiPublicV1SkillsAgentAgentRoute
}

const ApiPublicV1SkillsRouteChildren: ApiPublicV1SkillsRouteChildren = {
  ApiPublicV1SkillsIdRoute: ApiPublicV1SkillsIdRoute,
  ApiPublicV1SkillsAgentAgentRoute: ApiPublicV1SkillsAgentAgentRoute,
}

const ApiPublicV1SkillsRouteWithChildren =
  ApiPublicV1SkillsRoute._addFileChildren(ApiPublicV1SkillsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatgptSkillsRoute: ChatgptSkillsRoute,
  ClaudeSkillsRoute: ClaudeSkillsRoute,
  ContactRoute: ContactRoute,
  CursorSkillsRoute: CursorSkillsRoute,
  DevelopersRoute: DevelopersRoute,
  GithubCopilotSkillsRoute: GithubCopilotSkillsRoute,
  GrokSkillsRoute: GrokSkillsRoute,
  LibraryRoute: LibraryRoute,
  LicensesRoute: LicensesRoute,
  McpRoute: McpRoute,
  McpSkillsRoute: McpSkillsRoute,
  PerplexitySkillsRoute: PerplexitySkillsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuperhumanGoSkillsRoute: SuperhumanGoSkillsRoute,
  WordpressSkillsRoute: WordpressSkillsRoute,
  Char91DotwellKnownChar93ApiCatalogRoute:
    Char91DotwellKnownChar93ApiCatalogRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiSplatRoute: ApiSplatRoute,
  DocsApiRoute: DocsApiRoute,
  STokenRoute: STokenRoute,
  ApiPublicSkillsRoute: ApiPublicSkillsRouteWithChildren,
  ApiPublicV1CapabilitiesRoute: ApiPublicV1CapabilitiesRoute,
  ApiPublicV1SkillsRoute: ApiPublicV1SkillsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
