/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaudeSkillsRouteImport } from './routes/claude-skills'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as McpSkillsRouteImport } from './routes/mcp-skills'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as STokenRouteImport } from './routes/s.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeSkillsRoute = ClaudeSkillsRouteImport.update({
  id: '/claude-skills',
  path: '/claude-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const McpSkillsRoute = McpSkillsRouteImport.update({
  id: '/mcp-skills',
  path: '/mcp-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claude-skills': typeof ClaudeSkillsRoute
  '/library': typeof LibraryRoute
  '/licenses': typeof LicensesRoute
  '/mcp-skills': typeof McpSkillsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/s/$token': typeof STokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claude-skills': typeof ClaudeSkillsRoute
  '/library': typeof LibraryRoute
  '/licenses': typeof LicensesRoute
  '/mcp-skills': typeof McpSkillsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/s/$token': typeof STokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claude-skills': typeof ClaudeSkillsRoute
  '/library': typeof LibraryRoute
  '/licenses': typeof LicensesRoute
  '/mcp-skills': typeof McpSkillsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/s/$token': typeof STokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claude-skills'
    | '/library'
    | '/licenses'
    | '/mcp-skills'
    | '/sitemap.xml'
    | '/s/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claude-skills'
    | '/library'
    | '/licenses'
    | '/mcp-skills'
    | '/sitemap.xml'
    | '/s/$token'
  id:
    | '__root__'
    | '/'
    | '/claude-skills'
    | '/library'
    | '/licenses'
    | '/mcp-skills'
    | '/sitemap.xml'
    | '/s/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaudeSkillsRoute: typeof ClaudeSkillsRoute
  LibraryRoute: typeof LibraryRoute
  LicensesRoute: typeof LicensesRoute
  McpSkillsRoute: typeof McpSkillsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  STokenRoute: typeof STokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-skills': {
      id: '/claude-skills'
      path: '/claude-skills'
      fullPath: '/claude-skills'
      preLoaderRoute: typeof ClaudeSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-skills': {
      id: '/mcp-skills'
      path: '/mcp-skills'
      fullPath: '/mcp-skills'
      preLoaderRoute: typeof McpSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaudeSkillsRoute: ClaudeSkillsRoute,
  LibraryRoute: LibraryRoute,
  LicensesRoute: LicensesRoute,
  McpSkillsRoute: McpSkillsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  STokenRoute: STokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
